### ISSUE TITLE
Symlink should be the responsibility of the parent repo

### ISSUE THREAD

**Issue by chadfawcett** [TwoStoryRobot/prettier-config#1]
Having a symlink created on install can be error prone(as already seen in our CI environment). @chrisfosterelli came up with a better solution of having the parent repo have a relative symlink checked into git.

> @chrisfosterelli - Good point, if you uninstalled the file you’d still have to clean up the symlink. However I think [a relative symlink] is cleaner because:
> 
> 1. The symlink is explicitly the main project’s responsibility. The other way, the submodule creates the file for you but then it becomes your responsibility to clean up after the submodule if you want to remove it. 
> 
> 2. Because it’s tracked in git in this case it could also be removed for every developer at once as a tracked git commit along with when they remove the module from `package.json`.
> 
> 3. If someone accidentally `npm install`’s it outside of a project, it’s going to create a symlink _somewhere_ in their filesystem that they might not be aware of or remember to clean it up. Doesn’t have this issue with a parent project symlink.
> 
> 4. If someone accidentally `npm install -g`’s it there is going to be a root-owned symlink somewhere in `/usr` that likely isn’t going to get cleaned up. Again, doesn’t have this issue under this other way.
> 
> So primarily because ownership/cleanup is more clear and side-effects are less likely.

**Comment by chadfawcett** [comment]
This approach would also simplify our config repos, so we could have a single repo with eslint, prettier, etc rather than several.

**Comment by jonotron** [comment]
What if we changed the config to be in js via `prettier.config.js` with an exported config and then the parent repo can just source it in it's own `pretter.config.js`. This also provides for some simple extensibility.

See: https://github.com/prettier/prettier/issues/3146#issuecomment-341945300

**Comment by chadfawcett** [comment]
Resolved in #3
